---
apiVersion: v1
kind: Service
metadata:
  name: urban-take-home-test-node-app
  labels:
    app: urban-take-home-test-node-app
spec:
  type: NodePort
  selector:
    app: urban-take-home-test-node-app
  ports:
    - port: 3000
      targetPort: 3000
