name: build and push the app

on:
  push:
    branches:
      - master
  #   tags:
  #     - "v*-hello-world"
  # pull_request:
  #   branches:
  #     - 'master'

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: ghcr.io/thedatabaseme/hello-world
      #     flavor: latest=true
      #     tags: |
      #       type=ref,event=branch
      #       type=ref,event=pr
      #       type=semver,pattern={{version}}

      - name: Login to image repository
        # if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: application/.
          file: application/Dockerfile
          # push: ${{ github.ref_type == 'tag' }}
          # tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: wolfwolker/urban-take-home-test:latest
