name: build and push the app to the registry

on:
  push:
    branches:
      - master
    paths:
      - application/**
    tags:
      - '*'
  # pull_request:
  #   branches:
  #     - 'master'

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: ghcr.io/thedatabaseme/hello-world
      #     flavor: latest=true
      #     tags: |
      #       type=ref,event=branch
      #       type=ref,event=pr
      #       type=semver,pattern={{version}}

      - name: Login to image repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and push latest
        uses: docker/build-push-action@v3
        with:
          context: application/.
          push: true
          tags: ghcr.io/wolfwolker/urban-take-home-test-node-app:latest
          # file: application/Dockerfile
          # push: ${{ github.ref_type == 'tag' }}
          # tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push tag
        uses: docker/build-push-action@v3
        if: github.ref_type == 'tag'
        with:
          context: application/.
          push: true
          tags: ghcr.io/wolfwolker/urban-take-home-test-node-app:${{ github.ref_name }}
